### ISSUE TITLE
Member.yml blurbs can't use special chars like ':' 

### ISSUE THREAD

**Issue by jasonarita** [davisincubator/davisincubator.github.io#2]
## Problem

Members page fails to build when you use a special character (e.g. :, {, }, [, ], ,, &, etc.) in the blurb section. Github will send you a "Page Build Error" email and  **the member info and subsequent members** will not build/render on members page.

For example, [the colon+space (": ") in Ryan's blurb](https://github.com/davisincubator/davisincubator.github.io/blob/cfd6c02f4ea11cf8917a6a3f2e16bff62b9f2a44/_data/members.yml#L35) created a build error where his member info and Beth's member info both were not displayed.

`blurb: Still can't think of a blurb. What a boondoggle (credit: Emily).`

---
## Solution: Wrap entire blurb in double quotes to display special chars. [See below.](http://symfony.com/doc/current/components/yaml/yaml_format.html)

Strings containing any of the following characters must be quoted:

`:, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @, \`

The double-quoted style provides a way to express arbitrary strings, by using \ to escape characters and sequences. For instance, it is very useful when you need to embed a \n or a Unicode character in a string.

`"A double-quoted string in YAML\n"`

**Comment by rcphillips** [comment]
Ahhh makes sense! Thanks Jason!
